.travis.yml
setup.py

Attempt to enable testing in Travis.
I dropped nosetests requirement for now as I don't know of a need for it, and it makes this slightly simpler.

Travis tests

---

iris_grib/tests/__init__.py

@pelson as per https://github.com/SciTools/iris/pull/2037

Added specialised IrisGribTest.get_result_path

---

iris_grib/__init__.py
iris_grib/tests/unit/test_load_cubes.py

Unit test coverage for load cubes.

---

iris_grib/tests/__init__.py
iris_grib/tests/unit/test_load_cubes.py
iris_grib/tests/unit/test_save_messages.py

Unit test for save_messages.

---

iris_grib/tests/unit/test_as_pairs.py
iris_grib/tests/unit/test_save_messages.py

Unit test as_pairs

---

iris_grib/tests/unit/test_GribWrapper.py

Unit test GribWrapper.

---

iris_grib/tests/unit/test_as_messages.py

Unit test as_messages.

---

iris_grib/tests/unit/__init__.py
iris_grib/tests/unit/load_rules/__init__.py
iris_grib/tests/unit/load_rules/test_convert.py

Unit tests for load_rules.

---

.coveragerc
.travis.yml

Added test coverage loveliness.

Test coverage with coveralls.

---

iris_grib/__init__.py
iris_grib/tests/unit/test_GribWrapper.py
iris_grib/tests/unit/test__load_generate.py
iris_grib/tests/unit/test_load_cubes.py

Remove the deprecated auto-regularise behaviour from `GribWrapper`

Remove GribWrapper auto-regularise.

---

iris_grib/tests/unit/test_GribWrapper.py

Hmm don't quite understand how this came about, but here is the patch to fix master :confused:

Fix grib wrapper edition 1 test.

---

iris_grib/__init__.py
iris_grib/_save_rules.py
iris_grib/load_rules.py

Closes https://github.com/SciTools/iris-grib/issues/8

Remove inherited Iris deprecations.

---

iris_grib/_load_convert.py
iris_grib/_save_rules.py
iris_grib/tests/unit/load_convert/test_product_definition_template_40.py
iris_grib/tests/unit/save_rules/test_product_definition_template_40.py

Port of https://github.com/SciTools/iris/pull/2020
Closes https://github.com/SciTools/iris-grib/issues/14.

Port Iris PDT40 support.

---

iris_grib/_load_convert.py
iris_grib/_save_rules.py
iris_grib/tests/unit/load_convert/test_product_definition_template_10.py
iris_grib/tests/unit/save_rules/test__product_definition_template_8_10_and_11.py
iris_grib/tests/unit/save_rules/test_product_definition_template_10.py

Product definition template 10 has all the keys of pdt 8 but with an additional "percentileValue" key.

Add pdt 10

---

iris_grib/_load_convert.py
iris_grib/tests/unit/grib_phenom_translation/__init__.py
iris_grib/tests/unit/grib_phenom_translation/test_grib_phenom_translation.py
iris_grib/tests/unit/load_convert/test_convert.py

Add a ported test from iris.
Fix the _load_convert method to avoid type checking.

Iris import

---

environment.yml

Produces readthedocs output.
( but actual docs content still needs improving )

Tweak conda dependencies for readthedocs build.

---

docs/conf.py
docs/index.rst
docs/ref/grib_phenom_translation/grib_phenom_translation.rst
docs/ref/index.rst
docs/ref/iris_grib.rst
docs/ref/message/message.rst
environment.yml

Get sphinx docs for the whole api.
The results should good enough for a first release : **shout if they're not...**
**DO NOT MERGE**
Incorporates #53 and #54.  Possibly needs rebasing when those are in.

Full sphinx docs

---

.travis.yml
iris_grib/_grib_cf_map.py

new translations and changed translations from metarelate

updated translations

---

iris_grib/_save_rules.py
iris_grib/tests/unit/save_rules/test_product_definition_template_1.py

Add the functionality to save to product definition template  1 
> 'individual ensemble forecast, control and  perturbed, at a horizontal level or in a horizontal layer at a point in time')

Add save to pdt 1 

---

iris_grib/_load_convert.py
iris_grib/tests/unit/load_convert/test_reference_time_coord.py

Fix interpretation of significanceOfReferenceTime=0.

---

iris_grib/_load_convert.py
iris_grib/tests/unit/load_convert/test_product_definition_template_10.py
iris_grib/tests/unit/load_convert/test_product_definition_template_11.py
iris_grib/tests/unit/load_convert/test_product_definition_template_15.py
iris_grib/tests/unit/load_convert/test_statistical_cell_method.py

Only supports spatial processing code 0 = "whole cell, no interpolation".

Support for pdt 4.15.

---

environment.yml
iris_grib/_load_convert.py
iris_grib/_save_rules.py
iris_grib/message.py
iris_grib/tests/unit/load_convert/test_grid_definition_template_12.py
iris_grib/tests/unit/load_convert/test_grid_definition_template_20.py
iris_grib/tests/unit/load_convert/test_grid_definition_template_30.py
iris_grib/tests/unit/load_convert/test_grid_definition_template_40.py
iris_grib/tests/unit/load_convert/test_grid_definition_template_90.py
iris_grib/tests/unit/load_convert/test_product_definition_template_0.py
iris_grib/tests/unit/load_convert/test_product_definition_template_15.py
iris_grib/tests/unit/load_convert/test_product_definition_template_32.py
iris_grib/tests/unit/load_convert/test_unscale.py
iris_grib/tests/unit/message/test_GribMessage.py
iris_grib/tests/unit/save_rules/test_grid_definition_template_0.py
iris_grib/tests/unit/save_rules/test_grid_definition_template_1.py

This won't work until an Iris 2 can be found on conda-forge

Changes ported from Iris#2607

---

iris_grib/_load_convert.py
iris_grib/tests/integration/load_convert/test_load_hybrid_height.py
iris_grib/tests/results/unit/load_cubes/load_cubes/reduced_raw.cml

Spotted an off-by-one goof in the loading code.
This was inherited from (i.e. was already wrong in) the  pre-existing load-Hybrid-Pressure code.

Fix level index

---

docs/ref/release_notes.rst

Entry into the What'sNew regarding this addition: https://github.com/SciTools/iris-grib/pull/113

added entry about irregular lambert conformal grids

---

iris_grib/__init__.py

Currently blocked waiting for required PRs to be merged.

bump version number to 0.13

---

.travis.yml

Follow-up on https://github.com/SciTools/iris-grib/pull/123

Use ecCodes for Travis CI

---

iris_grib/__init__.py

I thought we should update thing version string since this definitely not v0.15

Update version string for 0.14.1

---

iris_grib/_grib_cf_map.py

translation updates from metarelate

metadata translations may 2019

---

iris_grib/__init__.py
iris_grib/message.py

A mergeback has not been done since the 0.14.1 release and so the changes included in #149 needs to be merged back onto master

0.14.x mergeback onto master

---

iris_grib/_grib_cf_map.py

update following:
https://github.com/metarelate/metOcean/issues/95
closes #160

https://github.com/metarelate/metOcean/issues/95

---

iris_grib/_load_convert.py
iris_grib/_save_rules.py
iris_grib/tests/integration/load_convert/test_load_hybrid_coords.py
iris_grib/tests/integration/save_rules/test_save_hybrid_coords.py
iris_grib/tests/results/unit/load_cubes/load_cubes/reduced_raw.cml

Closes #150 
I have also convinced myself that the indexing before was correct, based on looking at some data produced from ECMWF, rather than our own sample data
@pp-mo Are you able to review?

Revert pv level indexing change

---

iris_grib/_load_convert.py
iris_grib/_save_rules.py
iris_grib/grib_phenom_translation.py
iris_grib/tests/results/unit/load_cubes/load_cubes/reduced_raw.cml
iris_grib/tests/unit/grib_phenom_translation/test_grib_phenom_translation.py
iris_grib/tests/unit/load_convert/test_translate_phenomenon.py
iris_grib/tests/unit/save_rules/test_set_discipline_and_parameter.py

Label unknown phenomena with a 'GRIB_CODING' attribute

---

docs/ref/release_notes.rst
iris_grib/__init__.py
iris_grib/tests/integration/load_convert/test_sample_file_loads.py

**WIP**
do not merge until #203 is resolved
**NOTE:** includes a small tweak to remove redundant code, which should have been done in #200

Release 0x15x1

---

docs/index.rst
docs/ref/grib_phenom_translation/grib_phenom_translation.rst

Small changes + fix to complete the docs for 0.16

Update version in index; new module docs content.

---

docs/ref/release_notes.rst

Tiny fix (sorry about this).
When done, I will cut the actual release tag.

Fix RC date in release notes (about to cut).

---

.travis.yml
docs/ref/release_notes.rst
iris_grib/__init__.py
iris_grib/_grib1_load_rules.py
iris_grib/_load_convert.py
iris_grib/_save_rules.py
iris_grib/tests/results/integration/load_convert/data_section/TestGDT30/lambert.cml
iris_grib/tests/results/integration/load_convert/sample_file_loads/lambert_grib1.cml
iris_grib/tests/results/integration/load_convert/sample_file_loads/lambert_grib2.cml
iris_grib/tests/unit/grib1_load_rules/test_grib1_convert.py
iris_grib/tests/unit/load_convert/test_satellite_common.py
requirements/ci/py36.yml
requirements/ci/py37.yml
requirements/core.txt

Merge back v0.16.0.  Version bumped to 0.17.dev0.
This PR replaces #248

Merge back v0.16.0

---

README.rst

This PR adds further badges to the `README.rst` :+1:

add badges

---

docs/ref/release_notes.rst

Small change, just wanted to make sure the date was today's date.

Correct date of 0.17.1 release

---

CONTRIBUTING.md

See SciTools/.github#19 for details.

Update contributing guidelines in line with v5 SciTools CLA

---

.pre-commit-config.yaml
iris_grib/_save_rules.py
iris_grib/grib_phenom_translation.py
iris_grib/tests/unit/load_convert/test_translate_phenomenon.py
pyproject.toml

Configure for mypy

---

.github/workflows/ci-manifest.yml
MANIFEST.in

This pull-request enables automated manifest checking as part of a GHA.
TODO: Post merge - add badge to `README`

add manifest gha

---

MANIFEST.in

This pull-request adds `*.toml` files to the sdist manifest.

add toml to manifest

---

README.md

add iris grib logo to readme

---

docs/index.rst

Improve formatting for the conda and pip commands in the documentation.

Improve formatting.

---

MANIFEST.in
codecov.yml

This pull-request adds `codecov` configuration.

add codecov configuration

---

CONTRIBUTING.md
docs/ref/release_notes.rst
pyproject.toml

This pull-request targets PR #478 to fix the new issues raised by the latest version of `codespell`

fix codespell

---

.pre-commit-config.yaml
src/iris_grib/__init__.py
src/iris_grib/_grib1_load_rules.py
src/iris_grib/message.py

Looks like I made a mistake merging #567 
But it also seems that the required automatic fixes which a pre-commit run produces are not included in the pre-commit update PR.  Not sure if that is intended + should work, or what.

Fixes for recent merge-with-fails

---

.github/workflows/refresh-lockfiles.yml
src/iris_grib/tests/unit/load_convert/test_product_definition_template_0.py

Ironically, testing against latest-released Iris is now  causing us trouble also !

Update to latest refresh-lockfiles shared action.

---

.pre-commit-config.yaml
docs/index.rst
pyproject.toml
src/iris_grib/message.py

Address repo-review checks
