SciTools/iris-grib

iris_grib/tests/unit/message/__init__.py, iris_grib/tests/unit/message/test_GribMessage.py, iris_grib/tests/unit/message/test_Section.py, iris_grib/tests/unit/message/test__DataProxy.py, iris_grib/tests/unit/message/test__MessageLocation.py, iris_grib/tests/unit/message/test__RawGribMessage.py
Porting `iris.tests.unit.fileformats.grib.message` to `iris_grib`
=> Unit tests for iris_grib.message

iris_grib/__init__.py, iris_grib/_save_rules.py
This PR removes the `hindcast_workaround` from the `GribWrapper`, in preparation for making it `GRIB1` specific. See #36.
=> Remove GribWrapper hindcast_workaround.

iris_grib/tests/unit/load_convert/test_grid_definition_template_4_and_5.py, iris_grib/tests/unit/load_convert/test_grid_definition_template_5.py, iris_grib/tests/unit/load_convert/test_product_definition_template_31.py
Use the `iris_grib.tests.IrisGribTest.patch` convenience method.
=> Tidy unit test patching.

iris_grib/__init__.py, iris_grib/_load_convert.py, iris_grib/load_rules.py, iris_grib/tests/unit/__init__.py, iris_grib/tests/unit/load_convert/test_convert.py, iris_grib/tests/unit/load_rules/test_convert.py, iris_grib/tests/unit/load_rules/test_grib1_convert.py, iris_grib/tests/unit/test_GribWrapper.py
This PR forces the `GribWrapper` to be `GRIB1` specific, and subsequently purges all `GRIB2` rules from `iris_grib.load_rules.py`
=> Edition 1 for GribWrapper and load_rules.

iris_grib/__init__.py
Patching this into iris as a direct replacement for ```iris.fileformats.grib``` will currently cause a circular import.
Because :
* importing ```iris``` imports ```iris.fileformats```
* importing ```iris.fileformats``` imports ```iris_grib```
* importing ```iris_grib``` imports ```iris.fileformats.rules```  (see existing code below)
N.B. we think this probably also means we shouldn't regard iris as a _dependency_ of iris_grib.
Maybe an optional dependency ?
=> Defer import of iris to avoid circularity.

iris_grib/_load_convert.py
to fix potential bug when significance of reference time indicates a time, thus a time bounds, within PDT8
=> pdt8 sigRefTime

iris_grib/_save_rules.py
Adds a call for the save rules function for PDT10 to `_save_rules.product_definition_section`. This ensures that the PDT10 save rules function is called when a GRIB message described by PDT10 is passed to the saver.
Corrects an omission from #44 and fixes #50.
Note: does not (currently) contain the tests I suggested in #50 that would be beneficial to ensuring such omissions are harder to make in future.
=> Add save plumbing for pdt10

docs/index.rst
As Iris will automatically use iris-grib if it can, it's worth a little section on this within the docs.
=> Add section on connectivity to Iris

setup.py
The `setup.py` is not correctly specifying the `package_data` for `iris_grib` i.e. the `results` of the `iris_grib.test` is missing.
=> Correctly populate setup.py package_data.

iris_grib/_save_rules.py, iris_grib/tests/__init__.py, iris_grib/tests/unit/save_rules/test_grid_definition_section.py, iris_grib/tests/unit/save_rules/test_grid_definition_template_30.py
No tests yet, will add them shortly.
False eastings/northings are not supported for Lambert Conformal in GRIB, so they are ignored on save. Doing this doesn't lose any information about the locations of the points though, since GRIB stores the longitude and latitude of the first point in the grid.
=> Add support for Lambert Conformal saving

iris_grib/_load_convert.py
Closes #71.
This is the least intrusive change I can come up with that addresses the problem of threads.local usage. ``threads.local`` in itself is not a bad thing - it just needs to be initialised appropriately. That would be a more significant change here (and would require some care to avoid treading on settings that a user wishes to override, not to mention the performance cost).
=> Remove use of threads.local as a means of storing options.

iris_grib/__init__.py, iris_grib/_load_convert.py
Newer versions of numpy don't allow floats to be used as indices to arrays, even if they are integer-valued. This PR makes the tests pass (plus iris integration tests) with newer version of numpy, but I have not assessed other places in the code which may cause errors but are not caught by tests.
=> Prevent usage of floats as indices to numpy arrays due to deprecation

iris_grib/__init__.py
Reported version string was not right when "1.10.0" was tagged.
So with this change I'm aiming to move on and define a "1.10.1" instead.
As usual, when merged, I'll then tag "1.10.1" and create another PR moving version string to "1.11.0-dev".
@marqh I think we have also not been bothering with version branches here, e.g. in this case "1.10.x" ??
=> Version to 1.10.1 for release.

iris_grib/__init__.py
My previous change #80  was a goof !
the ".x" form is suitable for branch naming, and **_not_** a reported version string.
=> Amended version string to form 'major.minor+1.0-DEV'.

.travis.yml, environment.yml, iris_grib/__init__.py, iris_grib/_load_convert.py, iris_grib/_save_rules.py, iris_grib/message.py, iris_grib/tests/results/unit/load_cubes/load_cubes/reduced_raw.cml, iris_grib/tests/unit/grib1_load_rules/test_grib1_convert.py, iris_grib/tests/unit/load_convert/test_ellipsoid.py, iris_grib/tests/unit/message/test_GribMessage.py, iris_grib/tests/unit/save_rules/test_data_section.py, iris_grib/tests/unit/test_GribWrapper.py, setup.py
I've done this with very little understanding of the original rationale for integrating iris_grib back into iris, so I may have missed a key detail.
=> Port the changes from iris.fileformats.grib back into iris_grib.

iris_grib/__init__.py, iris_grib/_save_rules.py, iris_grib/message.py, iris_grib/tests/results/unit/load_cubes/load_cubes/reduced_raw.cml, iris_grib/tests/unit/load_convert/test_reference_time_coord.py, iris_grib/tests/unit/message/test_GribMessage.py, iris_grib/tests/unit/message/test__DataProxy.py, iris_grib/tests/unit/save_rules/test_data_section.py, iris_grib/tests/unit/test_load_cubes.py
Bring iris_grib up-to-date with recent changes to Iris, 
to use masked-arrays instead of nan masking in Dask (Dask v 0.13).
=> Dask masked fix

iris_grib/__init__.py
Let's cut v0.12.0, to release the changeover to eccodes.
When we're agreed to this, I'll cut a release from it
( and then re-bump the version string of course... )
=> Version string for v.0.12.0

.travis.yml
**WIP**
Test have been failing since it tests against iris-master, but was also relying on "iris/minimal-conda-requirements.txt", which is now defunct.
We "ought" to be testing against the latest Iris release, not master, in any case.
I think this was not doing so as it predated our first usable Iris 2 release.
Hopefully we now have a usable Iris v2 on conda-forge, so we should now test against that.
=> Test against latest conda-forge iris.

.travis.yml
This PR updates the .travis.yml to pick up the latest iris (v2.1) from conda-forge by making the following changes:
- unpin the version of numpy
- unpin the version of cartopy
- remove an unnecessary `iris=master` statement
=> Test against latest conda-forge iris

docs/ref/release_notes.rst, iris_grib/_load_convert.py, iris_grib/message.py, iris_grib/tests/unit/load_convert/test_grid_definition_template_10.py, iris_grib/tests/unit/load_convert/test_grid_definition_template_30.py
There was not support in iris-grib for loading data from grib2 files in the Mercator projection. This pull request addresses that by adding `grid_definition_template_10` to `_load_convert.py`.
Related to #95.
=> Support for loading grid_definition_template_10 (Mercator projection)

iris_grib/_save_rules.py, iris_grib/tests/unit/save_rules/__init__.py, iris_grib/tests/unit/save_rules/test_grid_definition_template_10.py
Adds functionality to save cubes on the Mercator projection to GRIB2, grid definition template 10.
Thanks to @kaedonkers for doing most of the work represented here!
=> Save Mercator Grid Definition Template

.coveragerc, iris_grib/__init__.py, iris_grib/_iris_mercator_support.py, iris_grib/_load_convert.py, iris_grib/_save_rules.py, setup.py
Popped a little function in the setup.py to look for iris 2.1 because that would be best, but if it's not available then it will install using iris 2.0 (or later).
Also added the eccodes dependency.  gribapi lives in python-eccodes, but I guess the (official?) package name is actually just eccodes.
=> Soft deps in setup

.travis.yml
- Added `--explicit` to conda env list so that we can grab the environment manifest of each run to reproduce it.
- Added `conda info -a` to list all info.  Not committed to this addition, might be worthwhile though.
=> added explicit flag to conda env list

setup.py
Replaced 'eccodes' with 'python-eccodes' in setup.py install_requires section.  Necessary for installation success.
=> corrected python-eccodes requirement in install_requires

.travis.yml, iris_grib/__init__.py, iris_grib/_save_rules.py, iris_grib/message.py
The eccodes 2.10 release includes Python 3 support.
This PR includes Python 3 in the testing matrix and thus highlights outstanding issues with iris-grib/eccodes/Python3
Known issues with Python 3 that work fine in Python 2:
**TESTS:** integration.save_rules.test_save_hybrid_coords (all tests in file)
**2.i) files with hybrid factory - problem loading orography field during factory creation**
files: iris_grib/tests/testdata/faked_sample_hh_grib_data.grib2 and faked_sample_hp_grib_data.grib2
**TESTS:** integration.load_convert.test_load_hybrid_coords (all tests in file) and integration.round_trip.test_hybrid_coords_round_trip (all tests in file)
**2.ii)) Can load in file as cube, when trying to call the data it fails**
files: iris_grib/tests/testdata/*.grib2, (excet CB which does work) …
=> Get iris-grib working in Python 3 !

.travis.yml, iris_grib/__init__.py, iris_grib/message.py
Eccodes v2.13.0 was just released, so this is to test iris-grib with that release.
Furthermore, eccodes-python has been updated such that things like `grib_get_double_array` returns arrays as we would expect, rather than a list, and as such I have pulled out those related workarounds.
FYI @bjlittle
=> Test most recent eccodes release

iris_grib/_load_convert.py, iris_grib/tests/unit/load_convert/test_product_definition_section.py, iris_grib/tests/unit/load_convert/test_product_definition_template_31.py
product_definition_section will no longer always try to populate the fixed surface arguments for translate_phenomenon - not available in some templates, in which case populate with None
Ran iris-grib unit tests afterwards - 364 passed, 21 were ignored as they needed external data (total 385)
=> Granularity for fixed surface arguments

iris_grib/_save_rules.py, iris_grib/tests/unit/save_rules/test_set_fixed_surfaces.py
Add depth variable to allow GRIB conversion of surface fields with depth coordinate, e.g. of UM fieldsfiles for soil moisture (lbuser4=8223) or soil temperature (lbuser4=8225).
=> Depth coordinate

iris_grib/_load_convert.py, iris_grib/tests/unit/load_convert/test_calculate_increment.py, iris_grib/tests/unit/load_convert/test_grid_definition_template_0_and_1.py, iris_grib/tests/unit/load_convert/test_grid_definition_template_40.py
This fix allows iris to obey the 'resolutionAndComponentFlags' value within GRIB files. This value specifies whether iris should be looking for i/j increments within the given GRIB file, and if they aren't specified (value of 0 is set) provides a method of calculating the increments via other means.
=> Fix to read grib files obeying 'resolutionAndComponentFlags'

.travis.yml, environment.yml
I think we should consider dropping Python 2 support. 
Due to the confusing nature of Python 2/3 support from `eccodes`/`eccodes-python`/`python-eccodes`, having Python 2 and Python 3 support means that the recipe/requirements will be horribly complicated.
We could simplify this by dropping Python 2. 
And anyway, Python 2 EoL is around the corner!! 
Dropping Python 2 support would mean we would have to make the next release a major release (iris grib 1.0) and remove all the Python 2 stuff (six etc)
Thoughts @bjlittle @pp-mo ?
=> Drop Python 2 Testing

docs/ref/release_notes.rst
Much to my surprise, it turns out we have release notes in iris-grib docs! 
This updates the docs to include notes about the 0.14.1 release, which I missed when I did that release)
I've made this change to the v0.14.x branch in case we do another 0.14 release, but once it is in, we can merge it into master.
Note the build of the docs is broken for some reason ? (I've capture it here #163 )
=> Add release notes for 0.14.1 release (GH-162)

setup.py
Pip installs seem to fail because the Python dependency is eccodes-python, not eccodes, if I'm understanding this correctly.
=> pip dependency is eccodes-python, not eccodes

setup.py
In preparation for the 0.15 release...
This PR: 
- Classify iris-grib as "Python 3 only" and drop other python 2 stuff 
- Add a message to explain the confusing eccodes installation (+ address outstanding comments from #154)
=> Modify setup.py to drop Py 2 support

docs/ref/release_notes.rst
I wrote up a summary of what changed in the 0.15 release.
The question is, does this go in before or after we cut the 0.15 release?
=> Add release notes for 0.15 release

iris_grib/__init__.py
Note that this is pointing at the new v0.15.x branch 
Any further development on the v0.15.x branch would be bug fixes that would released as part of 0.15.1 hence the new version string of '0.15.1dev0'
=> Bump version to 0.15.1dev0 (v0.15.x branch)

iris_grib/__init__.py
Note that this is pointing at the master branch
I'm assuming we are not ready for a major release yet (i.e. no iris-grib v1) so the next release will be iris-grib 0.16
=> Bump version to 0.16.0dev0 (master branch)

environment.yml, iris_grib/tests/integration/round_trip/test_hybrid_coords_round_trip.py, iris_grib/tests/unit/grib1_load_rules/test_grib1_convert.py
This PR makes some minor changes that allow the latest Iris-GRIB to be installed alongside the latest Iris, including ensuring that the Iris-GRIB tests can run.
_Note that Iris-GRIB includes a pep8 test, but pep8 is not included in [environment.yml](https://github.com/SciTools/iris-grib/blob/master/environment.yml) since it is not a core requirement. In the past, pep8 would be included with a full Iris install, but that is no longer the case since Iris was switched to black syntax, so running the tests from the command line may error on the pep8 test depending on the user's install. pep8 is however installed during the Travis tests._
=> Latest Iris Compatibility

iris_grib/tests/integration/round_trip/test_hybrid_coords_round_trip.py
Should allow test_hybrid_coords_round_trip.py to pass both with the existing Iris and also future releases
=> equalise_attributes compatibility for Iris 2.4 and also master.

environment.yml, iris_grib/tests/unit/test_save_messages.py
Previously a couple tests were failing with eccodes> 2.14 as eccodes was no longer raising an error when you give it a mock object.  This fixes those tests.
The environment currently resolves with eccodes 2.16
=> Get iris-grib tests passing with the latest version of eccodes

iris_grib/tests/unit/grib1_load_rules/test_grib1_load_translations.py
Tests ported from `iris.tests.test_grib_load_translations`.
Renamed and slightly simplified, as this (now) **only** tests the old GRIB-1 mechanisms.
A case could be made for combining this with the existing "sister" testcode `iris_grib.tests.unit.grib1_load_rules.test_grib1_convert`, and unifying the approaches.
But for GRIB1 I think this is strictly not worth it.  
Maybe when we [port GRIB1 to the new "strict" loader code](https://github.com/SciTools/iris-grib/issues/56) ?
=> Port test_grib_load_translations from iris

iris_grib/tests/unit/save_rules/test_product_definition_template_8.py, iris_grib/tests/unit/save_rules/test_set_discipline_and_parameter.py, iris_grib/tests/unit/save_rules/test_set_fixed_surfaces.py
Companion PR: https://github.com/SciTools/iris/pull/3666
The tests contained various unit tests so I split them up and put them in the correct places.
Note this doesn't include ALL the tests from iris/tests/test_grib_save_rules.py as there were some duplications. Check the iris PR for more information
=> Port tests from iris/tests/test_grib_save_rules.py from iris

iris_grib/tests/integration/iris_integration/__init__.py, iris_grib/tests/results/integration/iris_integration/__init__/TestCallbacks/grib_callback.cml
Not sure where to put this type of test.
I have created a new directory for integration tests specifically relating to Iris functionality, but I'm open to other suggestions!
Companion PR: https://github.com/SciTools/iris/pull/3665
=> Port tests from iris/tests/test_uri_ccallback.py

environment.yml, iris_grib/tests/unit/test_save_messages.py
Unfortunately, due to problems with saving in the latest eccodes version (2.16) (as shown [in these tests](https://travis-ci.org/SciTools/iris-grib/jobs/652968694?utm_medium=notification&utm_source=github_status)), we will have to pin back to using an older version of eccodes.
This is effectively undoing the changes in #189
=> Pin eccodes to avoid bad version

iris_grib/tests/integration/save_rules/test_grib_save.py
Companion PR: https://github.com/SciTools/iris/pull/3669
Basically a lift and shift of the tests in iris/tests/integration/test_grib_save.py other than the minor necessary changes such as inherit from `iris_grib.tests.IrisGribTest` rather than `iris.tests.IrisTest`
I just moved it to a file called iris_grib/tests/integration/save_rules/test_grib_save.py  as I thought that would be the easiest to review, but I could move it somewhere more sensible, iris_grib/tests/integration/save_rules/__init__.py for example.
=> Port tests from iris/tests/integration/test_grib_save.py

environment.yml, iris_grib/__init__.py, iris_grib/message.py, iris_grib/tests/unit/message/test__DataProxy.py, setup.py
Change that parallels https://github.com/SciTools/iris/pull/3659
**NOTE:** 
This contains a [temporary copy](https://github.com/SciTools/iris-grib/blob/fbe926137dafea6eac4db908d7f1c18f56f35002/iris_grib/__init__.py#L33) of the [key Iris routine](https://github.com/SciTools/iris/blob/9b8f9cbf943b2c659dcae2765e1cab089cabc645/lib/iris/util.py#L918) that enables this fix.
This can be removed when Iris 2.4 is out.
Not clear if we should merge this as-is, or wait for that ?
=> Fix dask2 proxies 

iris_grib/tests/integration/iris_integration/test_pickle_message.py
Depends on special functionality in `iris.tests.integration.test_pickle`, from which it imports.
Companion removing code from iris : https://github.com/SciTools/iris/pull/3671
**NOTE:** does at present not perform the desired testing, because the wanted functionality is currently broken, i.e. grib-based cubes cannot be pickled + restored.
#202 created to record this problem
=> Port pickling test from Iris.

iris_grib/tests/integration/load_convert/test_sample_file_loads.py, iris_grib/tests/results/integration/load_convert/sample_file_loads/3_layer.cml, iris_grib/tests/results/integration/load_convert/sample_file_loads/earth_shape_0.cml, iris_grib/tests/results/integration/load_convert/sample_file_loads/earth_shape_1.cml, iris_grib/tests/results/integration/load_convert/sample_file_loads/earth_shape_2.cml, iris_grib/tests/results/integration/load_convert/sample_file_loads/earth_shape_3.cml, iris_grib/tests/results/integration/load_convert/sample_file_loads/earth_shape_4.cml, iris_grib/tests/results/integration/load_convert/sample_file_loads/earth_shape_5.cml, iris_grib/tests/results/integration/load_convert/sample_file_loads/earth_shape_6.cml, iris_grib/tests/results/integration/load_convert/sample_file_loads/earth_shape_7.cml, iris_grib/tests/results/integration/load_convert/sample_file_loads/earth_shape_grib1.cml, iris_grib/tests/results/integration/load_convert/sample_file_loads/ineg_jneg.cml, iris_grib/tests/results/integration/load_convert/sample_file_loads/ineg_jpos.cml, iris_grib/tests/results/integration/load_convert/sample_file_loads/ipos_jneg.cml, iris_grib/tests/results/integration/load_convert/sample_file_loads/ipos_jpos.cml, iris_grib/tests/results/integration/load_convert/sample_file_loads/lambert_grib1.cml, iris_grib/tests/results/integration/load_convert/sample_file_loads/lambert_grib2.cml, iris_grib/tests/results/integration/load_convert/sample_file_loads/missing_values_grib2.cml, iris_grib/tests/results/integration/load_convert/sample_file_loads/polar_stereo_grib1.cml, iris_grib/tests/results/integration/load_convert/sample_file_loads/reduced_gg_grib2.cml, iris_grib/tests/results/integration/load_convert/sample_file_loads/reduced_ll_grib1.cml, iris_grib/tests/results/integration/load_convert/sample_file_loads/regular_gg_grib1.cml, iris_grib/tests/results/integration/load_convert/sample_file_loads/regular_gg_grib2.cml, iris_grib/tests/results/integration/load_convert/sample_file_loads/rotated.cml, iris_grib/tests/results/integration/load_convert/sample_file_loads/time_bound_grib1.cml, iris_grib/tests/results/integration/load_convert/sample_file_loads/time_bound_grib2.cml
Removed from iris : https://github.com/SciTools/iris/pull/3670
=> Import tests from iris.test.integration.test_grib load

iris_grib/tests/__init__.py, iris_grib/tests/integration/round_trip/test_grid_definition_section.py, iris_grib/tests/integration/round_trip/test_product_definition_section.py, iris_grib/tests/integration/save_rules/test_grib_save.py
Moved the test class iris.tests.TestGribMessage from iris. It should live in iris_grib as it is only used for iris_grib testing
Companion PR:  https://github.com/SciTools/iris/pull/3672
=> Port TestGribMessage from iris

environment.yml, iris_grib/_save_rules.py, iris_grib/tests/unit/save_rules/test_data_section.py, iris_grib/tests/unit/test_save_messages.py
Previously, we had a found a seg fault was being raised when trying to save out a large array.
This has now been *mostly* fixed in eccodes, but there is still an outstanding issue.
When trying to save out to GRIB, if the data is not float64, GRIB tries to cast it to float64. This is raising a seg fault!
As a temporary workaround, if we cast the data upfront, is seems to avoid the seg fault.
This PR is made up of 2 commits:
* the first commit unpins the eccodes requirements such that we get the latest eccodes, and also adds a test that explicitly tests saving int32, int64 and float32 (all of which would need casting to doubles). As you can see from the travis testng, this raises a seg fault
* the second commit adds the *temporary workaround* to cast the data to int64 upfront.
Note it turns …
=> Latest eccodes + workaround seg fault when saving

iris_grib/tests/__init__.py, iris_grib/tests/integration/load_convert/test_load_hybrid_coords.py, iris_grib/tests/integration/round_trip/test_WAFC_mapping_round_trip.py, iris_grib/tests/integration/round_trip/test_hybrid_coords_round_trip.py, iris_grib/tests/integration/save_rules/test_save_hybrid_coords.py
This PR adds some simple testing infra-structure changes to support external test data.
The `iris-grib` package is not shipped with the test data within this repo, and as such, developers cannot easily test a packaged version of `iris-grib`. Note that, the tests themselves are indeed shipped with the `iris-grib` package.
This PR adds an `iris_grib.tests.skip_data` decorator and also allows developers to specify the external directory that contains the `iris-grib` data using the `GRIB_TEST_DATA_PATH` environment variable.
In addition to this, developers may also set the `GRIB_TEST_NO_DATA` environment variable to explicitly skip tests (via the `skip_data` decorator) that require said external test data.
=> external grib test data skipper and hook

iris_grib/_load_convert.py, iris_grib/tests/unit/load_convert/test_statistical_cell_method.py
Add support for loading GRIB2 files using template 4.8 in which the time increment between successive fields used in statistical processing is not defined.
=> Add support for missing timeIncrement in template 4.8

iris_grib/_save_rules.py, iris_grib/tests/unit/save_rules/test_set_fixed_surfaces.py
IMHO we should be rounding ***any*** time we convert a float value to a scaled integer.
See: #211
However, it looks like that is awkward and will get in the way of the 0.16 release, so I think it's not worth it now.
=> Correct rounding of vertical coordinates.

environment.yml, iris_grib/tests/integration/format_interop/__init__.py, iris_grib/tests/integration/format_interop/test_name_grib.py, iris_grib/tests/integration/format_interop/test_pp_grib.py, iris_grib/tests/results/integration/name_grib/NAMEII/0_TRACER_AIR_CONCENTRATION.cml, iris_grib/tests/results/integration/name_grib/NAMEII/1_TRACER_DOSAGE.cml, iris_grib/tests/results/integration/name_grib/NAMEII/3_TRACER_DRY_DEPOSITION.cml, iris_grib/tests/results/integration/name_grib/NAMEII/4_TRACER_TOTAL_DEPOSITION.cml, iris_grib/tests/results/integration/name_grib/NAMEIII/0_TRACER_AIR_CONCENTRATION.cml, iris_grib/tests/results/integration/name_grib/NAMEIII/1_TRACER_AIR_CONCENTRATION.cml, iris_grib/tests/results/integration/name_grib/NAMEIII/2_TRACER_DRY_DEPOSITION.cml, iris_grib/tests/results/integration/name_grib/NAMEIII/3_TRACER_WET_DEPOSITION.cml, iris_grib/tests/results/integration/name_grib/NAMEIII/4_TRACER_DEPOSITION.cml
These are ported directly across from [these iris integration tests](https://github.com/SciTools/iris/tree/be9e2ff703e4a87f2c2533e86bd06aa402563b80/lib/iris/tests/integration/format_interop).
The aim of taking these tests out of Iris is so that we can avoid ***any*** need for iris-grib within Iris' own tests.
(not *quite* there yet, but coming soon...)
That linkage is a headache because at present *each requires the other* for testing :  Therefore, any breaking change (that requires parallel changes to both) can prevent both from passing tests, until both cut new releases.
----
NOTE: migrating these tests here still leaves open a possible ***future*** dependency problem ...
If in future we "split out" either of these other file-formats (name + pp) to a separate package, as we have done …
=> Tests for saving other-format data into grib : ported from Iris.

iris_grib/_load_convert.py, iris_grib/tests/results/integration/load_convert/data_section/TestImport/gdt90_with_bitmap.cml, iris_grib/tests/unit/load_convert/test_grid_definition_template_90.py
Ready to go now. I think.
Closes #222
=> Changes to gdt90 load.

docs/ref/release_notes.rst
Writeups for changes since 0.15.0, since we don't seem to have updated the whatsnew with 0.15.1 changes.
This is intended to be almost-ready for release, but...
* I am assuming that #223 is going in
* the actual release date will need writing in
I have tried to use style closer to the newer Iris whatsnews.  
Please highlight if more could be done in that way.
**temporary docs-build can be viewed [here](https://pp-iris-grib.readthedocs.io/en/whatsnew_16/ref/release_notes.html)**
=> Whatsnew v0.16

.travis.yml
Rename Iris test-version options, and enable all to check action.
This will also demonstrate testing against latest release
-- but then some tests will fail
When we get to merge this F-B back, it is because we have an actual Iris 3.0 release.
In that case, this should start to work.
=> Cosmetic change : rename the travis iris-test-version options

docs/ref/release_notes.rst, iris_grib/__init__.py, requirements/ci/py36.yml, requirements/ci/py37.yml, requirements/core.txt
Now basing this against the release branch "0.16.x", which is branched from the feature branch "f__test-iris-master"
This PR now modifies that to specifically test against the Iris 3.0.0rc0 release-candidate from `conda-forge/iris_rc`
The changes here are specific to the 0.16 release and will ***not*** go back onto master.
=> Version 0.16 release candidate

iris_grib/__init__.py, requirements/ci/py36.yml, requirements/ci/py37.yml
This fixes the RTD docs-build error which emerged following the cut of the original 0.16.0rc0 pre-release tag.
Given the error seen in the attempt to re-spin #224 today, we suspect those errors will come through here too
(something to do with ellipsoid definitions changing)
So we will probably want to wait until that is fixed before merging this ...
=> Add 'main' conda-forge channel, needed for docs builds.

requirements/ci/py36.yml, requirements/ci/py37.yml, requirements/core.txt
Updating to pick up Iris 3.0 release + test against it.
I have suspicions that we will need to add some Iris test dependencies into our depenencies here, to get tests working.
(E.G. "requests" ??).
But I want to check the need before adding extra deps
=> Fixdeps v16 iris3

iris_grib/_save_rules.py
**WIP**
Aiming to remove a workaround introduced in #208, supposedly now [fixed in python-eccodes](https://github.com/SciTools/iris-grib/pull/208#issuecomment-667335469).
So far, have re-checked that the original problem is replicable, having forced the old python-eccodes version, and removed the fix.  This triggered a segfault in the `tests.integration.round_trip.test_grid_definition_section.TestGDT5`.  It *should* also hit this in  `tests/unit/save_rules/test_data_section.TestNonDoubleData` (but that is not run before the crash happens).
**Then**, removed the version pin, now testing with 2.18.0 and python-eccodes 2020.06.0.
This should have been ok, but at present the original crash is still occurring .
**Current Status** : skipped out the GDT5 test, temporarily, to enable the intended …
=> Remove fix

docs/ref/release_notes.rst, iris_grib/__init__.py
Final changes to docs + release-string, 
ready to tag v0.16.0 release
=> Docstest 0v16

.cirrus.yml
This PR addresses the issue raised in https://github.com/conda/conda/issues/10596, as a workaround.
=> conda workaround in cirrus-ci for bad linux kernel version

iris_grib/_load_convert.py, iris_grib/tests/unit/load_convert/test_calculate_increment.py, iris_grib/tests/unit/load_convert/test_grid_definition_template_0_and_1.py
Per regulation 92.1.8, longitudes are limited to the range 0 to 360 degrees. This PR adds support for calculating `iDirectionIncrement` when not given (i.e. `resolutionAndComponentFlags` bit 3 is 0) where `longitudeOfFirstGridPoint` and `longitudeOfLastGridPoint` span the prime meridian in GDTs 0 and 40 and siblings.
=> Add support for reg 92.1.8 where lon increment not given

iris_grib/_load_convert.py, iris_grib/tests/unit/load_convert/test_data_representation_section.py
We recently had a user who wanted to load in data with grib data template number 42, i.e. CCSDS with compression, which we currently do not support.
The data decompression is all done in eccodes, so all we need to get this new template working is
* ensure we have a build of eccodes which was built with AEC enabled (the conda-forge build of eccodes [already has this enabled](https://github.com/conda-forge/eccodes-feedstock/blob/master/recipe/build.sh#L33)),
* add `42` to the list of supported template numbers
then when iris-grib loads in the data from the grib file, it goes via eccodes, which handles the decompresssion, and so returns a numpy array as normal.
I have kept the code change to iris-grib very lightweight (so I didn't check that the eccodes version running was built with AEC …
=> Add data template number 42 to the list of supported templates

docs/conf.py, docs/index.rst, docs/ref/release_notes.rst, iris_grib/__init__.py
Following the same pattern as was done in #244 
This:
* updates the release notes to include the 0.17 release, and
* updates the version string.
Regarding the release notes, I haven't included *every* PR. I skipped #258, #259, #262 as they all seemed a bit to minor to include
Readthedocs build: https://iris-grib.readthedocs.io/en/doctest_0v17/
=> Add release notes and update version number

CONTRIBUTING.md
The Iris dev guide has moved - update the link to the new location
=> Fix Iris dev guide link

.cirrus.yml, iris_grib/__init__.py, iris_grib/message.py, iris_grib/tests/unit/message/test__DataProxy.py, noxfile.py
Replacing https://github.com/SciTools/iris-grib/pull/282
As I needed a new branch
=> Various testing fixes

docs/conf.py, docs/index.rst, docs/ref/release_notes.rst, iris_grib/__init__.py
This PR performs the mergeback of 0.18.x branch back to main after the release of 0.18.0 earlier this week.
I also have updated the version number to now be 0.19.dev0
=> Mergeback 0.18.x branch to main

iris_grib/_load_convert.py, iris_grib/tests/unit/load_convert/test_grid_definition_template_12.py
Have been able to confirm that this behaviour handles a file as expected, thanks to @MoseleyS and @edwardccsteele.
=> Transverse Mercator support negative scanning

.github/workflows/refresh-lockfiles.yml
Similar to https://github.com/SciTools/iris/pull/5036
This will use a reusable workflow to run the refresh lockfile job.
~Note I have also added env.yml and lockfiles for Python 3.9 and 3.10~
=> Use reusable workflow for refresh lockfile job

iris_grib/_grib1_load_rules.py, iris_grib/tests/unit/grib1_load_rules/test_grib1_convert.py
Addresses #321 by correcting the calculation of the `period` in `forecast_period` coordinates with bounds. Currently the code tries to repeat a conversion of the values for the bounds into hours which results in an incorrect value. In addition the units of the `forecast_period` coordinate are not set to `hours` even though the values are converted to hours.
I suspect the testing I've done could be expanded / improved so I'm particularly keen for feedback which could help improve the coverage.
=> Correct bounded forecast period calculation

iris_grib/__init__.py, iris_grib/_load_convert.py, iris_grib/_save_rules.py, iris_grib/message.py, iris_grib/tests/integration/save_rules/test_grib_save.py, iris_grib/tests/unit/__init__.py, iris_grib/tests/unit/grib1_load_rules/test_grib1_convert.py, iris_grib/tests/unit/grib1_load_rules/test_grib1_load_translations.py, iris_grib/tests/unit/message/test_Section.py, iris_grib/tests/unit/message/test__RawGribMessage.py, iris_grib/tests/unit/save_rules/__init__.py, iris_grib/tests/unit/save_rules/test__product_definition_template_8_10_and_11.py, iris_grib/tests/unit/save_rules/test_data_section.py, iris_grib/tests/unit/save_rules/test_grid_definition_template_12.py, iris_grib/tests/unit/save_rules/test_identification.py, iris_grib/tests/unit/save_rules/test_product_definition_template_1.py, iris_grib/tests/unit/save_rules/test_product_definition_template_10.py, iris_grib/tests/unit/save_rules/test_product_definition_template_11.py, iris_grib/tests/unit/save_rules/test_product_definition_template_15.py, iris_grib/tests/unit/save_rules/test_product_definition_template_40.py, iris_grib/tests/unit/save_rules/test_product_definition_template_8.py, iris_grib/tests/unit/save_rules/test_reference_time.py, iris_grib/tests/unit/save_rules/test_set_discipline_and_parameter.py, iris_grib/tests/unit/save_rules/test_set_fixed_surfaces.py, iris_grib/tests/unit/save_rules/test_set_time_increment.py, iris_grib/tests/unit/save_rules/test_set_time_range.py, iris_grib/tests/unit/test_GribWrapper.py, iris_grib/tests/unit/test_save_messages.py
The [gribapi has been deprecated for a little while now](https://www.ecmwf.int/en/newsletter/152/news/end-road-grib-api) and replaced by [eccodes](). There's a bit of [guidance around the migration](https://confluence.ecmwf.int/display/ECC/GRIB-API+migration) but its pretty much a find/replace of `gribapi` -> `eccodes` and `grib_` -> `codes_`.
I've run the tests with the [current version of iris-test-data](https://github.com/SciTools/iris-test-data/tree/3306ae94956bc73b45576080a3ffb98ff9a9f1ad) and everything now passes.
There are a couple of references to early versions gribapi not handling certain use cases, but at the moment I've been unable to work out if they can be removed.
=> Convert gribapi to eccodes

.github/workflows/refresh-lockfiles.yml
This PR pins the `refresh-lockfiles` GHA to a specific version of the [scitools/workflows](https://github.com/SciTools/workflows/releases/tag/2023.03.0).
=> use workflows version for refresh-lockfiles ci

iris_grib/__init__.py, iris_grib/message.py, iris_grib/tests/unit/test_GribWrapper.py
These changes allow the correct calculation of the message offset on both Windows and Linux.
There are three additional test errors introduced as part of these changes (see below - only tested on Linux so far). These are all related to `grib_message` being a string rather than an integer - I'm not particularly familiar with GRIB, so I'm not sure if this is a peculiarity of the tests or that one would expect to encounter a message as a string when loading a file.
```bash
======================================================================
ERROR: test_reduced_proxy_args (unit.test_GribWrapper.Test_deferred_proxy_args)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/net/home/h02/dbentley/defence_applications/tda_source_code/gi …
```
=> alter calculation of offset

requirements/core.txt
PyPI's [`eccodes-python`](https://pypi.org/project/eccodes-python/) has now been deprecated and we are instructed to use `eccodes` instead (currently at 1.6.1 so please pin if needed).
Closes https://github.com/SciTools/iris-grib/issues/356
:beers:
=> replace deprecated `eccodes-python` PyPI package with new `eccodes` in core requirements

iris_grib/_iris_mercator_support.py
This pull-request addresses the following noisy deprecation warnings:
```bash
../iris-grib/iris_grib/_iris_mercator_support.py:21: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
```
and
```bash
../site-packages/setuptools/_distutils/version.py:345: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
```
Replacing the using of the deprecated `disutils.version` with `packaging.version` instead.
=> Drop deprecated distutils.version for packaging.version

iris_grib/_save_rules.py, iris_grib/message.py, iris_grib/tests/unit/save_rules/test_grid_definition_template_4.py, iris_grib/tests/unit/save_rules/test_grid_definition_template_5.py, requirements/core.txt, requirements/py310.yml, requirements/py311.yml, requirements/py39.yml
This pull-request updates `iris-grib` to cater within changes in the latest version of `eccodes`.
Due to this change in `eccodes` behaviour, I've defensively introduces a minimum pin for both `eccodes` and `python-eccodes`.
Note that, this PR is targeting the `auto-update-lockfiles` branch, which is the base branch of pull-request #354.
=> Fix for eccodes>=2.32.1 and python-eccodes>=1.6.1

.cirrus.yml, iris_grib/message.py, iris_grib/tests/integration/iris_integration/test_pickle_message.py, iris_grib/tests/integration/load_convert/test_data_section.py, iris_grib/tests/results/integration/load_convert/data_section/TestDataProxy/data_representation__no_bitsPerValue.cml
This pull-request extends the capability of the `iris_grib.message._DataProxy` to detect and auto-generate missing data payload for a GRIB2 message.
The scenario is that the message data payload is all zero, and rather than serialize this within the message, thus increasing the footprint, an application can generate the data at runtime whenever the Data Representation Section [5] has `bitsPerValue=0` and an empty Data Section [7].
Failure to support this extension results in no encoded Data Section [7] within a `iris_grib.message._RawGribMessage` causing a `KeyError` traceback within the user script. The impact of this is that an N-D Iris cube can be loaded but whenever at least one GRIB2 message has such missing data, touching the cube data will result in this failure.
Reference: …
=> Auto-generate zero data for missing data payload

iris_grib/_save_rules.py, iris_grib/tests/integration/save_rules/test_grid_definition_section.py, iris_grib/tests/unit/save_rules/test_grid_definition_template_140.py
**Description**
Saving of cubes on the Lambert Azimuthal Equal Area (LAEA) projection is added.
The LAEA template is described here: https://codes.ecmwf.int/grib/format/grib2/templates/3/140/
It is very similar to the Lambert Conformal projection specification in template_30, and so the coding was based on that.
https://codes.ecmwf.int/grib/format/grib2/templates/3/30/
**Associated Issue**
https://github.com/SciTools/iris-grib/issues/344
=> Save LAEA grid

.readthedocs.yml, readthedocs.yml, requirements/py311.yml
The docs have not been built successfully for a while.  This updates the `.readthedocs.yml` file.
Updates based upon the Iris config https://github.com/SciTools/iris/blob/main/.readthedocs.yml.  I think there was no need for the post checkout actions though so we removed.
Further tweaks may be needed but this will get it building cleanly.
I have also enabled readthedocs building the docs for PR's so this the docs should not go stale again.
Fix for https://github.com/SciTools/iris-grib/issues/365.
=> Fix the docs building on readthedocs

.readthedocs.yml, docs/conf.py, docs/index.rst, docs/ref/release_notes.rst, readthedocs.yml, requirements/py311.yml
Pulled in the recent docs fix from main.
Update the front-page version number and the release notes page to the v0.19 state -- which was not done at v0.19.0 release.
Intending to tag this as `v0.19.1`, to get a sensible docs-build up (and which will become the 'stable' endpoint).
Will then merge back (though now expecting to generate some conflicts).
=> v0x19 docs update

.readthedocs.yml, docs/conf.py, docs/index.rst, docs/ref/release_notes.rst
**NOTE:** this is a mergeback, and could use a merge commit.
It seems this never got done after the v0.19 release, 
in consequence (for example) the docs on main currently still say it is [at version 0.18](https://github.com/SciTools/iris-grib/blob/b620e2e461706f21ec48a9ea6160514b4303cea0/docs/index.rst?plain=1#L6)
=> v019x mergeback

requirements/py310.yml, requirements/py311.yml, requirements/py39.yml, requirements/test.txt
This pull-request adds the `iris-sample-data` package dependency, as required by doctests.
=> add iris-sample-data test dependency

.github/workflows/ci-tests.yml, noxfile.py
This PR undoes a temporary workaround introduced by #415 for a limitation encountered when using the `nose` package on a GHA runner.
As we have now migrated away from `nose` and are using `pytest`, this workaround is now no longer necessary 👍
=> fix ci-tests nose workaround

.pre-commit-config.yaml
This pull-request changes to source URL for the `blacken-docs` pre-commit hook, as recommended by `repo-review`.
Resolves the following `repo-review` non-compliance:
=> fix blacken-docs hook url

.pre-commit-config.yaml, pyproject.toml
We have some exceptions to the rule (some of which we can address), but it's best that we adopt the `repo-review` hook now to ensure that we don't regress.
=> adopt repo-review pre-commit hook

src/iris_grib/__init__.py, src/iris_grib/message.py, src/iris_grib/tests/unit/test__load_generate.py
`iris._lazy_data.as_lazy_data` has changed :  See [iris#5801.](https://github.com/SciTools/iris/pull/5801)
Current failing tests against iris latest,
e.g. see https://github.com/SciTools/iris-grib/actions/runs/8892392519/job/24416350591
=> Provide masked/unmasked meta for calls to 'as_lazy_data' 

docs/Makefile, docs/conf.py, docs/ref/release_notes.rst
Minor updates to the docs:
- Force docs build warnings to be errors 
- Force doc build to continue if there are errors
- Updated an intersphinx mapping
- Added the `:orphan:` tag to the release notes file , else it raises a warning (toctree will now ignore this file)
=> Ensure no warnings on docs build

pyproject.toml
https://github.com/SciTools/iris-grib/issues/496
=> Remove MyPy redundant-expr error

docs/ref/release_notes.rst, requirements/py310.yml, requirements/py311.yml, requirements/py312.yml, src/iris_grib/_load_convert.py, src/iris_grib/_save_rules.py, src/iris_grib/message.py, src/iris_grib/tests/unit/load_convert/test_forecast_period_coord.py, src/iris_grib/tests/unit/load_convert/test_product_definition_template_0.py, src/iris_grib/tests/unit/load_convert/test_product_definition_template_15.py, src/iris_grib/tests/unit/load_convert/test_product_definition_template_40.py, src/iris_grib/tests/unit/load_convert/test_statistical_forecast_period_coord.py, src/iris_grib/tests/unit/save_rules/__init__.py, src/iris_grib/tests/unit/save_rules/test_grid_definition_template_0.py, src/iris_grib/tests/unit/save_rules/test_grid_definition_template_1.py, src/iris_grib/tests/unit/save_rules/test_grid_definition_template_10.py, src/iris_grib/tests/unit/save_rules/test_grid_definition_template_12.py, src/iris_grib/tests/unit/save_rules/test_grid_definition_template_140.py, src/iris_grib/tests/unit/save_rules/test_grid_definition_template_20.py, src/iris_grib/tests/unit/save_rules/test_grid_definition_template_30.py, src/iris_grib/tests/unit/save_rules/test_grid_definition_template_4.py, src/iris_grib/tests/unit/save_rules/test_grid_definition_template_5.py
Fixes for a couple of backwards-incompatibilities introduced in eccodes version 2.36
~N.B. this also tested OK against 2.35, for which [these lines](https://github.com/SciTools/iris-grib/blob/a4c52810b003cc231b4fa3c79f55a2e1b93444fa/src/iris_grib/message.py#L28-L29) are required.~
~However, it's not clear how old an eccodes this will support, since `indicatorOfUnitOfTimeRange` is only aliassed on loading --  **_not_** in saving, where setting it always+only uses `indicatorOfUnitForForecastTime` (the new form).~
From their release page, v2.33 is when `indicatorOfUnitForForecastTime` was introduced, which we now write on saves.
Tested against eccodes v2.33 and v2.32 : confirmed the new code works with 2.33 but **_not_** 2.32.
As stated in whatsnew + updated requirements yml files.
N.B. the …
=> Eccodes 2v36

.pre-commit-config.yaml, docs/index.rst, docs/ref/iris_grib.rst, docs/ref/message/message.rst, pyproject.toml, src/iris_grib/__init__.py, src/iris_grib/_grib1_load_rules.py, src/iris_grib/_load_convert.py, src/iris_grib/_save_rules.py, src/iris_grib/grib_phenom_translation/_gribcode.py, src/iris_grib/message.py
Replaces #564 
Don't understand why this was needed, since the branch location is the same.
Seems like GitHub got confused somehow by my adding a commit + then removing it
=> Code qa refresh

src/iris_grib/_load_convert.py, src/iris_grib/tests/unit/load_convert/test__hindcast_fix.py
It seems that the only remaining problem for numpy2 is that the update to the code introduced [here in #578](https://github.com/SciTools/iris-grib/pull/578/files#r1866349413) was causing tests to fail, when actually run with numpy 2.
I had meant to keep that issue separate from the eccodes 2v38 one, but somehow I tripped over my own commits.
This PR fixes that, so when merged it should unblock #550 🤞
=> Support numpy2

.github/workflows/refresh-lockfiles.yml
This should resolve to pull in iris 3.11.1, which in turn pins dask to <2024.12, and  fixes the current pickling test problem.
That may only be a temporary fix, but it's in line with the decision for Iris 3.11.1
=> Update to refresh-lockfiles v2025.01.0 

docs/index.rst, docs/ref/release_notes.rst
As usual, we will create a new release branch just in case a bugfix might be needed.
This whatsnew update is the only change not already on main, and after release we'll subsequently merge this back. 
At that point, within the mergeback, we will also change the main documentation page version title to "v0.22 (unreleased)" to avoid confusion.
=> Release notes for v0.21, to support latest ecCodes.

src/iris_grib/tests/integration/iris_integration/test_pickle_message.py, src/iris_grib/tests/unit/message/test_pickle_message.py
Started off as a solution to recent test failures brought on from https://github.com/SciTools/iris/pull/6342, and ended up shuffling the furniture. 
This no longer relies on iris, which hopefully means iris-grib tests won't fail whenever something changes in iris. A couple of things to note:
- Should this still be placed in iris_integration tests? Presumably not.
- I've left in some commented code, which is bad form, but it's essentially a to-do. 
- The tests failing seem to be due to not running on pytest from what I can see, which begs the question, do we abandn this PR, and return to unit test and just fix the immediate failures?
=> Converted test_pickle_message to pytest, and removed reliance on Iris

pyproject.toml, requirements/py310.yml, requirements/py311.yml, requirements/py312.yml
This pull-request complies with [PEP639](https://peps.python.org/pep-0639/) for `setuptools`, also see [license and license-files](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license-and-license-files).
Additionally avoids the following `setuptools` deprecation warning:
```
!!
********************************************************************************
Please consider removing the following classifiers in favor of a SPDX license expression:
License :: OSI Approved :: BSD License
See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
********************************************************************************
!!
```
=> pep639: setuptools license and license-files fields

pyproject.toml, src/iris_grib/__init__.py, src/iris_grib/tests/integration/iris_integration/test_nc_attribute_handlers.py
N.B. this will not function until https://github.com/SciTools/iris/pull/6566 is merged,
since it uses the new tests provided there.
I think it **_should_** run once that is in, since we test against iris main branch.
Though we do also test against latest-release, and that will still fail until we update this...
Made into draft as not currently viable...
=> Import and run grib-dependent attribute handling tests from Iris.
